name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build - Server
      working-directory: ./server
      run: cargo build --verbose
    - name: Run tests - Server
      working-directory: ./server
      run: cargo test --verbose
    # find way to compile with v4l2
    # - name: Build - Client
    #   working-directory: ./client
    #   run: cargo build --verbose
    # - name: Run tests - Client
    #   working-directory: ./client
    #   run: cargo test --verbose
